
[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "table.sort(self.cards, function (a, b) return a.T.x + a.T.w/2 - 100*(a.pinned and a.sort_id or 0) < b.T.x + b.T.w/2 - 100*(b.pinned and b.sort_id or 0) end)"
position = "at"
payload = '''
table.sort(self.cards, function (a, b)
            local a_val = a.T.x + a.T.w/2 - 100*(a.pinned and a.sort_id or 0)
            local b_val = b.T.x + b.T.w/2 - 100*(b.pinned and b.sort_id or 0)

            a_val = a_val + 100*(a.pinned_right and a.sort_id or 0)
            b_val = b_val + 100*(b.pinned_right and b.sort_id or 0)
            
            return a_val < b_val
            
        end)
'''
match_indent = true
overwrite = false

## for Lovely 0.5.0 and above

# [[patches]]
# [patches.regex]
# target = "cardarea.lua"
# pattern = '''- 100\*\((\w+)\.pinned and (\w+)\.sort_id or 0\)'''
# position = "at"
# payload = '''
# $0 + 100*($1.pinned_right and $1.sort_id or 0)
# '''
# match_indent = true
# overwrite = false